.create table SimpleTable1(Id:int, Name:string)

.create table SimpleTable2(thing:dynamic)

.create table SimpleTable3(thing:dynamic)

.create table SimpleTable4(thing:dynamic)

.create table SimpleTable5(thing:dynamic)

.create table SimpleTable6(thing:dynamic)

.create table SimpleTable7(thing:dynamic)

.create table SimpleTable8(thing:dynamic)

.create table SimpleTable9(thing:dynamic)

.create table SimpleTable10(thing:dynamic)

.create table SimpleTable11(thing:dynamic)

.create table SimpleTable12(thing:dynamic)

.create table SimpleTable13(thing:dynamic)

.create table SimpleTable14(thing:dynamic)

.create table SimpleTable15(thing:dynamic)

.create table SimpleTable16(thing:dynamic)

.create table SimpleTable17(thing:dynamic)

.create table SimpleTable18(thing:dynamic)

.create table SimpleTable19(thing:dynamic)

.create table SimpleTable20(thing:dynamic)

.create table SimpleTable21(thing:dynamic)

.create table SimpleTable22(thing:dynamic)

.create table SimpleTable23(thing:dynamic)

.create table SimpleTable24(thing:dynamic)

.create table SimpleTable25(thing:dynamic)

.create table SimpleTable26(thing:dynamic)

.create table SimpleTable27(thing:dynamic)

.create table SimpleTable28(thing:dynamic)

.create table SimpleTable29(thing:dynamic)

.create table SimpleTable30(thing:dynamic)

.create table SimpleTable31(thing:dynamic)

.create table SimpleTable32(thing:dynamic)

.create table SimpleTable33(thing:dynamic)

.create table SimpleTable34(thing:dynamic)

.create table SimpleTable35(thing:dynamic)

.create table SimpleTable36(thing:dynamic)

.create table SimpleTable37(thing:dynamic)

.create table SimpleTable38(thing:dynamic)

.create table SimpleTable39(thing:dynamic)

.create table SimpleTable40(thing:dynamic)

.create table SimpleTable41(thing:dynamic)

.create table SimpleTable42(thing:dynamic)

.create table SimpleTable43(thing:dynamic)

.create table SimpleTable44(thing:dynamic)

.create table SimpleTable45(thing:dynamic)

.create table SimpleTable46(thing:dynamic)

.create table SimpleTable47(thing:dynamic)

.create table SimpleTable48(thing:dynamic)

.create table SimpleTable49(thing:dynamic)

.create table SimpleTable50(thing:dynamic)

.create table SimpleTable51(thing:dynamic)

.create table SimpleTable52(thing:dynamic)

.create table SimpleTable53(thing:dynamic)

.create table SimpleTable54(thing:dynamic)

.create table SimpleTable55(thing:dynamic)

.create table SimpleTable56(thing:dynamic)

.create table SimpleTable57(thing:dynamic)

.create table SimpleTable58(thing:dynamic)

.create table SimpleTable59(thing:dynamic)

.create table SimpleTable60(thing:dynamic)

